// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlLfrdE9SJp5Ir2Z-B2kjn6tEI2URm6Ow',
    appId: '1:1089189354887:web:5765f0dc9562eb14850722',
    messagingSenderId: '1089189354887',
    projectId: 'hair-app-1172f',
    authDomain: 'hair-app-1172f.firebaseapp.com',
    storageBucket: 'hair-app-1172f.firebasestorage.app',
    measurementId: 'G-K3NL653X86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOQbv5ee3bV7Pw-zlQz1nNmb1_05c50C4',
    appId: '1:1089189354887:android:fc0374ac11c3f43a850722',
    messagingSenderId: '1089189354887',
    projectId: 'hair-app-1172f',
    storageBucket: 'hair-app-1172f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSM5qCpBG6pVCYWKUhF5LO2GMQPxPe21w',
    appId: '1:1089189354887:ios:00ed662481a47f2f850722',
    messagingSenderId: '1089189354887',
    projectId: 'hair-app-1172f',
    storageBucket: 'hair-app-1172f.firebasestorage.app',
    iosBundleId: 'com.muratovaslan.hairApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSM5qCpBG6pVCYWKUhF5LO2GMQPxPe21w',
    appId: '1:1089189354887:ios:78c4a5b630cd2377850722',
    messagingSenderId: '1089189354887',
    projectId: 'hair-app-1172f',
    storageBucket: 'hair-app-1172f.firebasestorage.app',
    iosBundleId: 'com.example.hairApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlLfrdE9SJp5Ir2Z-B2kjn6tEI2URm6Ow',
    appId: '1:1089189354887:web:c129c942ff2bb363850722',
    messagingSenderId: '1089189354887',
    projectId: 'hair-app-1172f',
    authDomain: 'hair-app-1172f.firebaseapp.com',
    storageBucket: 'hair-app-1172f.firebasestorage.app',
    measurementId: 'G-G74XED94NP',
  );
}
